name: my first ci and cd
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 1. 拉代码
        uses: actions/checkout@v4
      - name: 2. 装 Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: 3. 跑测试
        run: python app.py
  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: 4. 远程部署到服务器
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            echo "成功登录服务器！"
            echo "这里可以写 git pull 和重启服务的命令"
